# Configuration file for key parameters in main.py

# Logging configuration
logging:
  log_directory: "Logs"  # Directory where log files will be stored
  log_level_file: "INFO"  # Logging level for log files (e.g., INFO, DEBUG)
  log_level_console: "INFO"  # Logging level for console output

# Motor IDs for pivots
motor_ids:
  pivots:  # Motor IDs for the two pivot motors
    FRONT_PIVOT: 7  # Front pivot motor
    REAR_PIVOT: 8  # Rear pivot motor

# Parameters for controlling the pivot motors
pivot_parameters:
  pivot_step: 5  # Step size for pivot control via D-pad (degrees per step)
  initial_front_angle: 180  # Initial angle for the front pivot motor (degrees)
  initial_rear_angle: 180  # Initial angle for the rear pivot motor (degrees)

# Controller configuration (e.g., for communication with motors)
controller:
  device_name: "/dev/ttyACM0"  # Device path for the controller connection
  baudrate: 1000000  # Baud rate for serial communication

# Reporting configuration
reporting:
  motor_position_interval: 10  # Interval (in seconds) for logging motor positions

# Velocity limits for different motor groups
velocity_limits:
  Pivot_Group: 4  # Maximum velocity for the pivot motors
  All_Motors: 200  # Global maximum velocity limit for all motors

# Profile velocity settings (predefined velocity configurations)
profile_velocities:
  Pivot_Group: 4  # Profile velocity for the pivot group
  All_Motors: 8  # Global profile velocity for all motors

# Hard limits for velocity (safety parameters)
hard_velocity_limit: 100  # Maximum allowable velocity for any motor
hard_profile_velocity_limit: 100  # Maximum allowable profile velocity for any motor

# Position limits for different parts of the robot
position_limits:
  Hinges:
    min_degrees: 45  # Minimum allowable hinge angle (degrees)
    max_degrees: 315  # Maximum allowable hinge angle (degrees)

# Control table addresses and lengths for different motor parameters
control_table:
  torque_enable:
    address: 64
    length: 1
  goal_velocity:
    address: 104
    length: 4
  goal_position:
    address: 116
    length: 4
  present_position:
    address: 132
    length: 4
  homing_offset:
    address: 20
    length: 4
  operating_mode:
    address: 11
    length: 1
  velocity_limit:
    address: 44
    length: 4
  profile_velocity:
    address: 112
    length: 4
  profile_acceleration:
    address: 108
    length: 4
  present_velocity:
    address: 128
    length: 4
  max_position_limit:
    address: 48
    length: 4
  min_position_limit:
    address: 52
    length: 4
  drive_mode:
    address: 10
    length: 1
  temperature_limit:
    address: 31
    length: 1
  max_voltage_limit:
    address: 32
    length: 2
  min_voltage_limit:
    address: 34
    length: 2
  pwm_limit:
    address: 36
    length: 2
  current_limit:
    address: 38
    length: 2
  acceleration_limit:
    address: 40
    length: 4
  shutdown:
    address: 63
    length: 1
  moving_status:
    address: 123
    length: 1
  moving:
    address: 122
    length: 1
  hardware_error_status:
    address: 70
    length: 1
  indirect_address_1:
    address: 168
    length: 2
  indirect_data_1:
    address: 224
    length: 1
  status_return_level:
    address: 68
    length: 1
  present_load:
    address: 126
    length: 2

# Motor groupings for synchronized and bulk write commands
motor_groups:
  Pivot_Group:  # Motors involved in pivoting
    - FRONT_PIVOT
    - REAR_PIVOT
  All_Motors:  # All motors in the system
    - FRONT_PIVOT
    - REAR_PIVOT
